### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by rjuju** [rjuju/pg_track_settings#2]
To keep track of the work to have a debian package.

**Comment by rjuju** [comment]
Work started in https://github.com/rjuju/pg_track_settings/commit/0d163067e59afe0cc6b0bba1ecd28aaf98d94d68

**Comment by rjuju** [comment]
@df7cb I started to work on a debian package.  could you check is this is ok?  FTR I compiled them locally, run the tests and didn't spot any problem.

**Comment by df7cb** [comment]
Hi, I'm currently on vacation and will likely not get to this until around July 14th. (Please poke me if I should forget after that.)

**Comment by rjuju** [comment]
Thanks! Enjoy your holidays, nothing's rushed here :)

**Comment by df7cb** [comment]
I pushed a few updates in #3.

The .sql files do not provide an upgrade path from 1.x to 2.0.0, is that intended?

**Comment by rjuju** [comment]
Thanks for the PR!

Indeed, I didn't provide an upgrade path from previous versions as this was a major rewrite.  I can fix that if needed, but since 2.0.0 has already been release, this should probably be done with a 1.1.0--2.0.1 and keep 2.0.0 as is.

**Comment by rjuju** [comment]
Hello @df7cb !  Is there anything else required for the 2.0.0 package?

**Comment by df7cb** [comment]
The problem with 2.0.0 is that the master branch has already non-`debian/` changes past the 2.0.0 tag, so building the package will fail with complaints about changed files. For 2.0.1, everything should be set I think.

**Comment by rjuju** [comment]
Oh I see, indeed.  Well, I'll work on a 2.1.1, and take the opportunity to add an upgrade path from 1.x to 2.1.1 just in case someone is interested.

**Comment by df7cb** [comment]
I needed a package example for a apt.postresql.org demo, and pg-track-settings was a perfect example so I did the missing steps to make the 2.0.0 packages real. I have a temporary branch elsewhere to revert the two non-2.0.0 changes to make dpkg-buildpackage happy, but I found one more missing bit (Architecture: all) with I'll PR in a minute.

**Comment by rjuju** [comment]
Thanks, that's a great news!

FTR I finished writing the upgrade scripts, but I need to do so more extra checks to make sure that I didn't miss anything.
